### ISSUE TITLE
Remove certificates from repo

### ISSUE THREAD

**Issue by kubitz** [achuth10/Traffic#1]
Hey, thanks for making your code available, currently trying to use greengrass for a project of mine. 

Just saw you left your device private keys and certificate in the repo. Would recommend adding them in the .gitignore, and removing them from the pushed code. 

Leaving them there could pose a security risk to your account, if they were not properly disabled.

**Comment by achuth10** [comment]
Thank you so much for letting me know, not sure how I missed this.
